#add your make here
#compiler
CC = gcc

#flags
CLFAGS = -Wall -Wextra -std=c11

#source file
SRC = src/main.c

#exec
OUT = todo

#default to -> a.out
all:
	$(CC) $(CFLAGS) -o $(OUT) $(SRC)

clean:
	rm -f $(OUT)
